name: CI

on:
  pull_request:
  push:
    branches: [main, develop, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Si tienes variables/secretos para build, añádelos con env: o secrets
      - name: Build
        run: npm run build
